version: '3'

networks:
  vaultwarden_net:
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  vaultwarden:
    image: vaultwarden/server:alpine
    # image: vaultwarden/server:testing-alpine
    restart: always
    container_name: vaultwarden
    networks:
      - vaultwarden_net
    volumes:
    - ${PWD}/vaultwarden:/data
    # - vaultwarden_vol:/data/
    - ${PWD}/utilities/backup.sh:/backup.sh:ro
    env_file:
    - ".env"
    environment:
    - BACKUP_SCHEDULE
    command: >
      sh -c 'apk --update --no-cache add sqlite
             ln -sf /proc/1/fd/1 /var/log/backup.log &&
             sed -i "/ash \\/backup\\.sh /d" /etc/crontabs/root &&
             echo "$BACKUP_SCHEDULE ash /backup.sh" >> /etc/crontabs/root && 
             crond -d 8 &&
             exec /start.sh'

  # mariadb:
  #   image: mariadb
  #   container_name: mariadb
  #   hostname: mariadb
  #   restart: always
  #   networks:
  #     - vaultwarden_net
  #   env_file:
  #   - ".env"
  #   volumes:
  #   # - ${PWD}/mariadb_vol:/var/lib/mysql
  #   - mariadb_vol:/var/lib/mysql
  #   - /etc/localtime:/etc/localtime:ro

  proxy:
    image: nginx:alpine
    restart: always
    container_name: proxy
    networks:
      - vaultwarden_net
    depends_on:
    - vaultwarden
    volumes:
    - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ${PWD}/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    container_name: cloudflared
    networks:
      - vaultwarden_net
    user: root
    entrypoint: cloudflared tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    depends_on:
    - proxy
    volumes:
    - ${PWD}/cloudflared:/etc/cloudflared:ro
    environment:
    - CLOUDFLARED_TOKEN

  watchtower:
    # Watchtower will pull down your new image, gracefully shut down your existing container 
    # and restart it with the same options that were used when it was deployed initially
    # https://github.com/containrrr/watchtower
    image: containrrr/watchtower
    restart: always
    container_name: watchtower
    networks:
      - vaultwarden_net
    depends_on: 
    - vaultwarden
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    env_file:
    - ".env"

# volumes:
#  vaultwarden_vol:
#  mariadb_vol: